### ISSUE TITLE
Syntax error in the executable

### ISSUE THREAD

**Issue by JankaGramofonomanka** [idris-community/inigo#37]
I can't run the `inigo` executable, I get this error:

```
/usr/local/bin/inigo:63
  } catch (e) { return 0n }
                       ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

my version of nodejs is 8.10.0.

By the way, it would be nice if it was stated in the README that you need nodejs to run inigo.

**Comment by alexhumphreys** [comment]
Hmm my node is `v16.5.0` and it's working ok, so you may need to try with a newer version.

And good call on the README! Want to open a PR for that change? Otherwise I'll probably get to it at some point.

**Comment by Z-snails** [comment]
Yep, you need node 10.4.0 for BigInt support (it would be good to mention that in the readme too).

**Comment by JankaGramofonomanka** [comment]
I updated to node v16.13.0 and it now runs but still doesn't work.
It prints the usage info, instead of initializing the project, which I described in issue #39.

**Comment by Z-snails** [comment]
Lets leave this open until someone fixes the README.
